# CLASSIC-8 Report Generation Configuration
# This file controls how crash log reports are generated

ReportSettings:
  # Report Format Selection
  # Options: "Standard", "Enhanced", "Auto"
  # - Standard: Basic report with essential information
  # - Enhanced: Advanced formatting without FCX data
  # - Auto: Automatically select based on FCX mode
  ReportFormat: "Auto"
  
  # Override format selection based on conditions
  FormatOverrides:
    # Use Enhanced format even without FCX if crash is complex
    UseEnhancedForComplexCrashes: true
    ComplexCrashThreshold: 5  # Number of suspects to trigger enhanced
    
    # Always use Standard format for specific scenarios
    ForceStandardFor:
      - QuickScan
      - BatchProcessing
      - APIRequests
  
  # FCX Mode Settings
  FCXMode:
    # Enable/disable FCX mode globally
    Enabled: false
    
    # Automatically enable FCX for specific games
    AutoEnableForGames:
      - "Fallout4"
      - "SkyrimSE"
    
    # FCX-specific report sections
    Sections:
      MainFilesCheck: true
      GameFilesCheck: true
      ExtendedModAnalysis: true
      PerformanceMetrics: true
      GameHints: true

# Template-specific Settings
Templates:
  Standard:
    # Standard template configuration
    MaxSuspectsShown: 10
    IncludeFormIds: true
    ShowPluginFlags: false
    
  Enhanced:
    # Enhanced template configuration
    MaxSuspectsShown: 20
    GroupSuspectsByPriority: true
    IncludeExecutiveSummary: true
    ShowPerformanceMetrics: true
    MaxGameHints: 3  # Game hints available without FCX
    SuggestFCXMode: true
    
  Advanced:
    # Advanced (FCX) template configuration
    MaxSuspectsShown: -1  # Show all
    IncludeAllSections: true
    MaxGameHints: 3
    ShowDetailedMetrics: true
    IncludeTechnicalDetails: true

# Output Settings
Output:
  # Output directory for reports
  ReportDirectory: "./Reports"
  
  # File naming pattern
  # Available variables: {filename}, {date}, {time}, {format}
  FileNamePattern: "CLASSIC-Report-{filename}-{date}-{time}.md"
  
  # Additional output formats
  AdditionalFormats:
    # Generate HTML version
    HTML:
      Enabled: false
      Template: "report.html"
    
    # Generate JSON for API consumption
    JSON:
      Enabled: false
      IncludeRawData: false
    
    # Discord webhook integration
    Discord:
      Enabled: false
      WebhookUrl: ""
      SendSummaryOnly: true

# Performance Settings
Performance:
  # Maximum processing time before switching to simpler template
  MaxProcessingTimeSeconds: 30
  
  # Batch processing settings
  BatchProcessing:
    # Use simpler templates for batch processing
    UseSimplifiedReports: true
    MaxConcurrentReports: 4

# User Experience
UserExperience:
  # Show report selection reason
  ExplainTemplateChoice: true
  
  # Example output:
  # "Using Enhanced template (FCX disabled, complex crash detected)"
  
  # Interactive mode
  Interactive:
    # Ask user for template preference
    AskForTemplate: false
    RememberChoice: true

# Feature Flags
FeatureFlags:
  # Enable experimental features
  ExperimentalTemplateEngine: false
  AsyncReportGeneration: true
  CacheCompiledTemplates: true

# Localization
Localization:
  # Report language
  Language: "en-US"
  
  # Available languages for templates
  AvailableLanguages:
    - "en-US"
    - "es-ES"
    - "fr-FR"
    - "de-DE"
    - "ja-JP"
    - "zh-CN"

# Debug Settings
Debug:
  # Include debug information in reports
  IncludeDebugInfo: false
  
  # Log template selection process
  LogTemplateSelection: true
  
  # Save intermediate data
  SaveIntermediateData: false
  IntermediateDataPath: "./Debug/ReportData"